function $userInfo(form) {
    form.attr('data-form-name','info')
    form.append('<h3>User info</h3>')
    form.append('<label for="name" class="name">Full name:</label><input id="name" class="name">')
    $('.name').wrapAll('<div class="row">')
    //let $username = $('#username')
    //$username.attr('data-parsley-minlength','4')
    //$username.attr('data-parsley-maxlength','20')
    //$username.attr('data-parsley-username-fill','')
    form.append('<label for="avatar" class="avatar">Avatar:</label><input id="avatar" class="avatar" type="file">')
    $('.avatar').wrapAll('<div class="row">')
    //let $username = $('#username')
    //$username.attr('data-parsley-minlength','4')
    //$username.attr('data-parsley-maxlength','20')
    //$username.attr('data-parsley-username-fill','')
    form.append('<label for="birth" class="birth">Avatar:</label><input id="birth" class="birth">')
    $('.birth').wrapAll('<div class="row">')
    //let $username = $('#username')
    //$username.attr('data-parsley-minlength','4')
    //$username.attr('data-parsley-maxlength','20')
    //$username.attr('data-parsley-username-fill','')
    form.append('<label for="gender" class="gender">Gender:</label>')
    form.append('<input class="gender" name="gender" value="male" type="radio">')
    form.append('<input class="gender" name="gender" value="female" type="radio">')
    $('.gender').wrapAll('<div class="row">')
    //let $username = $('#username')
    //$username.attr('data-parsley-minlength','4')
    //$username.attr('data-parsley-maxlength','20')
    //$username.attr('data-parsley-username-fill','')
    form.append('<label for="subscribe" class="subscribe">Subscribe:</label>')
    form.append('<input id="subscribe" class="subscribe" type="checkbox">')
    $('.subscribe').wrapAll('<div class="row">')
    //let $username = $('#username')
    //$username.attr('data-parsley-minlength','4')
    //$username.attr('data-parsley-maxlength','20')
    //$username.attr('data-parsley-username-fill','')
    form.append('<button type="submit" id="register">Save</button>')
    let $input = $('input')
    $input.attr('data-parsley-trigger','focusout')
    $input.attr('data-parsley-required','true')
    $input.wrap('<div class="col-75">')
    $('label').wrap('<div class="col-25">')
}

export {$userInfo}