import {$validateField} from './validate.js'

function $userInfo(form) {
    form.attr('data-form-name','info')
    form.append('<h3>User info</h3>')
    form.append('<label for="name" class="name label">Full name:</label><input id="name" class="name input">')
    $('.name').wrapAll('<div class="row">')
    let $fullName = $('#name')
    $fullName.attr('data-parsley-minlength','2')
    $fullName.attr('data-parsley-maxlength','50')
    form.append('<label for="avatar" class="avatar label">Avatar:</label><input id="avatar" class="avatar input" type="file">')
    $('.avatar').wrapAll('<div class="row">')
    let $avatar = $('#avatar')
    form.append('<label for="birth" class="birth label">Birthday:</label>')
    form.append('<input id="birth" class="birth input" placeholder="dd/mm/yyyy" pattern="/^([0-2][0-9]|(3)[0-1])(\\/)(((0)[0-9])|((1)[0-2]))(\\/)\\d{4}$/i">')
    $('.birth').wrapAll('<div class="row">')
    let $birth = $('#birth')
    $birth.attr('data-parsley-birth-validate','')
    form.append('<label for="gender" class="gender label">Gender:</label>')
    form.append('<input id="male" class="gender gen" name="gender" type="radio">')
    form.append('<label for="male" class="gender gen">Male</label>')
    form.append('<input id="female" class="gender gen" name="gender" type="radio">')
    form.append('<label for="female" class="gender gen">Female</label>')
    $('.gender').wrapAll('<div class="row">')
    $('.gen').wrapAll('<div class="col-75">')
    let $gender = $('input.gender')
    $gender.attr('data-parsley-required','true')
    form.append('<label for="subscribe" class="subscribe label">Subscribe:</label>')
    form.append('<input id="subscribe" class="subscribe input" type="checkbox">')
    let $subscribe = $('#subscribe')
    $subscribe.wrapAll('<div class="row">')
    form.append('<button type="submit" id="register">Save</button>')
    let $input = $('.input')
    let $label = $('.label')
    $input.attr('data-parsley-trigger','focusout')
    $input.attr('data-parsley-required','true')
    $subscribe.attr('data-parsley-required','false')
    $input.wrap('<div class="col-75">')
    $label.wrap('<div class="col-25">')

    $input.each(function () {
        $validateField($(this))
    })
}

export {$userInfo}